config/routes.rb
Rails.application.routes.draw do
  resources :states
  resources :fake_news
  resources :people
  resources :offices
  resources :populations
  resources :communications
  resources :parties
  resources :fonts
  resources :scales
  resources :powers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/communication.rb
class Communication < ApplicationRecord
  has_many :news_communications
  has_many :fake_news, through: :news_communications
end

app/models/fake_news.rb
class FakeNews < ApplicationRecord
  belongs_to :font
  belongs_to :scale
  belongs_to :population
  has_many :news_people
  has_many :people, through: :news_people
  has_many :news_communications
  has_many :communications, through: :news_communications
  has_many :news_states
  has_many :states, through: :news_states
  has_one_attached :image
end

app/models/font.rb
class Font < ApplicationRecord
  has_many :fake_news
end

app/models/news_communication.rb
class NewsCommunication < ApplicationRecord
  belongs_to :fake_news
  belongs_to :communication
end

app/models/news_person.rb
class NewsPerson < ApplicationRecord
  belongs_to :fake_news
  belongs_to :person
end

app/models/news_state.rb
class NewsState < ApplicationRecord
  belongs_to :fake_news
  belongs_to :state
end

app/models/office.rb
class Office < ApplicationRecord
  belongs_to :power
  has_many :people
end

app/models/party.rb
class Party < ApplicationRecord
  has_many :people
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :office
  belongs_to :party
  has_many :news_people
  has_many :fake_news, through: :news_people
end

app/models/population.rb
class Population < ApplicationRecord
  has_many :fake_news
end

app/models/power.rb
class Power < ApplicationRecord
  has_many :offices
end

app/models/scale.rb
class Scale < ApplicationRecord
  has_many :fake_news
end

app/models/state.rb
class State < ApplicationRecord
  has_many :news_states
  has_many :fake_news, through: :news_states
end

app/controllers/scales_controller.rb
class ScalesController < ApplicationController
  before_action :set_scale, only: [:show, :edit, :update, :destroy]

  # GET /scales
  # GET /scales.json
  def index
    @scales = Scale.all
  end

  # GET /scales/1
  # GET /scales/1.json
  def show
  end

  # GET /scales/new
  def new
    @scale = Scale.new
  end

  # GET /scales/1/edit
  def edit
  end

  # POST /scales
  # POST /scales.json
  def create
    @scale = Scale.new(scale_params)

    respond_to do |format|
      if @scale.save
        format.html { redirect_to @scale, notice: 'Scale was successfully created.' }
        format.json { render :show, status: :created, location: @scale }
      else
        format.html { render :new }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scales/1
  # PATCH/PUT /scales/1.json
  def update
    respond_to do |format|
      if @scale.update(scale_params)
        format.html { redirect_to @scale, notice: 'Scale was successfully updated.' }
        format.json { render :show, status: :ok, location: @scale }
      else
        format.html { render :edit }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scales/1
  # DELETE /scales/1.json
  def destroy
    @scale.destroy
    respond_to do |format|
      format.html { redirect_to scales_url, notice: 'Scale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scale
      @scale = Scale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scale_params
      params.require(:scale).permit(:description)
    end
end

app/helpers/fake_news_helper.rb
module FakeNewsHelper
end

app/helpers/fonts_helper.rb
module FontsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/helpers/scales_helper.rb
module ScalesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/scales/_form.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Area de cadastro</title>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag "vendor/bootstrap/css/bootstrap.min.css" %>

    <!-- Custom fonts for this template -->
    <%= stylesheet_link_tag "vendor/fontawesome-free/css/all.min.css" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" %>

    <!-- Custom styles for this template -->
    <%= stylesheet_link_tag "css/clean-blog.min.css" %>

  </head>

  <body>
    <!-- Page Header -->
    <header class="masthead altura" style="background-color: #232FB2">
      <div class="overlay "></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading centraliza">
              <h1 style="text-align: center">Escala de alcance da notícia</h1>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <%= form_with(model: scale, local: true) do |form| %>
              <% if scale.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(scale.errors.count, "error") %> prohibited this scale from being saved:</h2>

                  <ul>
                  <% scale.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="field">
                <%= form.label :Descrição %>
                <%= form.text_field :description %>
              </div>

              <div class="actions">
                <%= form.submit %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </article>

    <hr>
    <!-- Bootstrap core JavaScript -->
    <%= javascript_include_tag "vendor/jquery/jquery.min.js" %>
    <%= javascript_include_tag "vendor/bootstrap/js/bootstrap.bundle.min.js" %>

    <!-- Custom scripts for this template -->
    <%= javascript_include_tag "js/clean-blog.min.js" %>

  </body>

</html>

app/views/scales/edit.html.erb
<%= render 'form', scale: @scale %>

app/views/scales/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Area de cadastro</title>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag "vendor/bootstrap/css/bootstrap.min.css" %>

    <!-- Custom fonts for this template -->
    <%= stylesheet_link_tag "vendor/fontawesome-free/css/all.min.css" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" %>

    <!-- Custom styles for this template -->
    <%= stylesheet_link_tag "css/clean-blog.min.css" %>

  </head>

  <body>
    <!-- Page Header -->
    <header class="masthead altura" style="background-color: #232FB2">
      <div class="overlay "></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading centraliza">
              <h1 style="text-align: center">Escala de alcance da notícia</h1>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <table class="table">
              <thead>
                <tr>
                  <th>Descrição</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody style="">
                <% @scales.each do |scale| %>
                  <tr>
                    <td><%= scale.description %></td>
                    <td><%= link_to 'Show', scale %></td>
                    <td><%= link_to 'Edit', edit_scale_path(scale) %></td>
                    <td><%= link_to 'Destroy', scale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

            <br>

            <%= link_to 'Nova Escala', new_scale_path %>
          </div>
        </div>
      </div>
    </article>

    <hr>
    <!-- Bootstrap core JavaScript -->
    <%= javascript_include_tag "vendor/jquery/jquery.min.js" %>
    <%= javascript_include_tag "vendor/bootstrap/js/bootstrap.bundle.min.js" %>

    <!-- Custom scripts for this template -->
    <%= javascript_include_tag "js/clean-blog.min.js" %>

  </body>

</html>

app/views/scales/new.html.erb
<%= render 'form', scale: @scale %>

app/views/scales/show.html.erb
<div class="container" style="margin-top:3em">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Descrição:</strong>
    <%= @scale.description %>
  </p>

  <%= link_to 'Edit', edit_scale_path(@scale) %> |
  <%= link_to 'Back', scales_path %>
</div>